FROM node:18-alpine as builder

WORKDIR /app

COPY ./mosters/package*.json ./

RUN npm i --production

COPY ./mosters/* .

COPY ./posters ./posters

ENV POSTER_DIR=posters

EXPOSE 8080

CMD ["npm", "start"]